NODES = [
  { name: "master1", ip: "10.10.0.1", role: "control-plane", mem: 2048, cpu: 2 },
  { name: "worker1", ip: "10.10.0.2", role: "worker",        mem: 1024, cpu: 1 },
  { name: "worker2", ip: "10.10.0.3", role: "worker",        mem: 1024, cpu: 1 },
]
NUM_WORKERS = 4

Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |lv|
    lv.management_network_address = "10.10.0.0/24"
  end
  NODES.each do |n|
    config.vm.define n[:name] do |node|
      node.vm.box = "generic/ubuntu2204"
      node.vm.box_version = "4.3.12"
      node.vm.hostname = n[:name]
      node.vm.network "private_network", ip: n[:ip]

      node.vm.provider "libvirt" do |lv|
        lv.memory = n[:mem]
        lv.cpus = n[:cpu]
      end

      if n[:role] == "control-plane"
        node.vm.provision "shell", inline: <<-SHELL
          echo ">> Provisioning CONTROL-PLANE: #{n[:name]}"
        SHELL
      else
        node.vm.provision "shell", inline: <<-SHELL
          echo ">> Provisioning WORKER: #{n[:name]}"
        SHELL
      end
    end
  end
end
