Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "generic/ubuntu2204"
    master.vm.box_version = "4.3.12"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.50.10"
    master.vm.provider "libvirt" do |lv|
      lv.memory = 2048
      lv.cpus = 2
    end
  end

  config.vm.define "worker" do |worker|
    worker.vm.box = "generic/ubuntu2204"
    worker.vm.box_version = "4.3.12"
    worker.vm.hostname = "worker"
    worker.vm.network "private_network", ip: "192.168.50.11"
    worker.vm.provider "libvirt" do |lv|
      lv.memory = 2048
      lv.cpus = 2
    end
  end
end